export default {
  site: {
    title: "AI Engineering Research",
    description: "Searchable AI engineering research repository",
    baseUrl: "/",
    language: "en",
    siteUrl: "https://ai.echelonfoundry.com/",
  } /**/,
  repository: {
    name: "AI Engineering",
    sourceUrl: "https://github.com/kemiller2002/AI Engineering",
  },
  content: {
    include: ["**/*.md"],
    exclude: [
      "node_modules/**",
      "dist/**",
      "build/**",
      "build-reports/**",
      ".git/**",
      ".github/**",
      ".research-publisher/**",
      "coverage/**",
      "tmp/**",
      "temp/**",
      "input-documents/**",
      "prompts/**",
      "packages/**",
      "templates/**",
      "research/evaluation/fixtures/**",
      "content/disciplines/ai-engineering/handbook/engineering-workflows.md",
      "content/disciplines/ai-engineering/handbook/foundations.md",
      "content/disciplines/ai-engineering/handbook/research-engineering.md",
      "content/disciplines/ai-engineering/handbook/token-economics-and-context-engineering.md",
      "content/projects/ai-engineering-course/chapter-01/research/research-package-001-notes.md",
      "**/archive/**",
      "**/archives/**",
    ],
    drafts: false,
  },
  metadata: {
    mode: "compatible",
    strictInCI: true,
  },
  output: {
    directory: "dist",
    catalog: "data/research-catalog.json",
    diagnostics: "data/build-diagnostics.json",
  },
};
